### ISSUE TITLE
Needs update for 3.4.1

### ISSUE THREAD

**Issue by landryb** [georchestra/geonetwork_minimal_datadir#2]
Loading the default templates/schemas in an empty geonetwork from this datadir yields in a broken editor, either for a new metadata or editing a sample metadata:

```
 runtime_exceptionTemplate get-iso19139-title has not been definedXPathException 
```
indeed that's not defined in our minimal datadir:
```
[12/07 16:15] root@demo.thruxton:/srv/data/geonetwork $git grep get-iso19139-title
....nothing....
```
Defined in the schemas shipped in the geonetwork webapp:

```
$grep -r get-iso19139-title /srv/tomcat/georchestra/webapps/geonetwork/WEB-INF/data/config/
/srv/tomcat/georchestra/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/layout/utility-tpl.xsl:  <xsl:template name="get-iso19139-title"
```

**Comment by landryb** [comment]
Ofc, everything upstream was reindented, so it's impossible to figure out the actual changes...

**Comment by landryb** [comment]
The current schemas in our datadir yields this upon indexing:
```
2018-07-12 16:08:38,183 ERROR [geonetwork.index] - Indexing stylesheet contains errors: /srv/data/geonetwork/config/schema_plugins/iso19139/index-fields/index-subtemplate.xsl 
         Marking the metadata as _indexingError=1 in index
```
the given path ddesnt exist in the repo ?

**Comment by fvanderbiest** [comment]
You're right, and this is a blocker for 18.06 (one more)

**Comment by landryb** [comment]
Replacing everything under `config/schema_plugins` in the datadir by the contents of `geonetwork/WEB-INF/data/config/schema_plugins/*` allows me to create a new iso 19139 MD or to edit one of the sample iso 19139 MDs, but that's a *huge* hammer.

**Comment by landryb** [comment]
I *think* upstream schemas reference has to be merged from https://github.com/geonetwork/core-geonetwork/tree/3.4.x/schemas - the last merge we did was 68a55932 which picked up to geonetwork/core-geonetwork@23261c5

**Comment by landryb** [comment]
Seems that's less than 500 commits according to
```
geonetwork/core-geonetwork $git log --oneline --stat 23261c5..3.4.x schemas
```
 :) at that point i wonder if we'd better off extracting our changes and rebasing them on top of upstream....

**Comment by pmauduit** [comment]
Why not launching a georchestra-gn3.4 with an empty datadir and let the bootstrap process populating it ? I'm almost sure there are no custom georchestra modifications in the schemas.

**Comment by landryb** [comment]
To be tested/discuted but i think we had a few changes (which might still be relevant, or not) - but in that case we should just drop that repo or explicitely mark it as *not for 3.4/18.06*...

**Comment by pmauduit** [comment]
Digging out a newly generated datadir against this one, the only difference which pops in meld are the 3 thesauri as well as some evolutions coming from the 3.4.1 version (ATOM feeds, turkish translation), I think it is pretty safe to consider that the files coming from regular GN (more exactly from our GN fork) are legit.

**Comment by pmauduit** [comment]
I created a new branch gn3.4.1 on this repository, no issue encountered so far (tried the edit mode as well).

@landryb could you give it a try ?

**Comment by landryb** [comment]
Basic testing show it working fine, but two minor nits already:
  * d5f6f2f8 should be cherrypicked
  * `config/schemaplugin-uri-catalog.xml` should be removed from the repo, as it's regenerated at geonetwork startup - here i can see that you used /mnt/geonetwork_datadir when generating it :p
```
[18/07 14:53] root@demo.thruxton:/srv/data/geonetwork $git diff
diff --git a/config/schemaplugin-uri-catalog.xml b/config/schemaplugin-uri-catalog.xml
index e3b2bde..94001e4 100644
--- a/config/schemaplugin-uri-catalog.xml
+++ b/config/schemaplugin-uri-catalog.xml
@@ -8,9 +8,9 @@
                         we use this process to avoid having to make changes to GeoNetwork xslts
                         to include presentation xslts from schemas that are plugged in -->
   <!-- plug in schemas - come next - managed by schema.add/update/delete -->
-  <rewriteURI uriStartString="blanks/metadata-schema01" rewritePrefix="/mnt/geonetwork_datadir/config/schema_plugins/iso19139" />
-  <rewriteURI uriStartString="blanks/metadata-schema02" rewritePrefix="/mnt/geonetwork_datadir/config/schema_plugins/dublin-core" />
-  <rewriteURI uriStartString="blanks/metadata-schema03" rewritePrefix="/mnt/geonetwork_datadir/config/schema_plugins/csw-record" />
-  <rewriteURI uriStartString="blanks/metadata-schema04" rewritePrefix="/mnt/geonetwork_datadir/config/schema_plugins/iso19110" />
+  <rewriteURI uriStartString="blanks/metadata-schema01" rewritePrefix="/srv/data/geonetwork/config/schema_plugins/iso19139" />
+  <rewriteURI uriStartString="blanks/metadata-schema02" rewritePrefix="/srv/data/geonetwork/config/schema_plugins/csw-record" />
+  <rewriteURI uriStartString="blanks/metadata-schema03" rewritePrefix="/srv/data/geonetwork/config/schema_plugins/iso19110" />
+  <rewriteURI uriStartString="blanks/metadata-schema04" rewritePrefix="/srv/data/geonetwork/config/schema_plugins/dublin-core" />
```

**Comment by landryb** [comment]
Fwiw, geonetwork still allows anonymous users to download files that are *not* supposed to be available to anonymous users (ie 'download' in priviledges is unchecked). I had fixed it for our fork in #1 but it seems upstream still doesnt care about that issue, which i consider a security issue.

Will bring it again upstream.

**Comment by pmauduit** [comment]
> Will bring it again upstream.

sure, sorry for having forgotten this when I worked on the 3.4.1 integration.

**Comment by landryb** [comment]
Cf geonetwork/core-geonetwork#2981 for the new issue.. which is awkward.

**Comment by landryb** [comment]
Afaict reading the code, the default status (public vs private) for uploaded files is set to public here: https://github.com/georchestra/geonetwork/blob/georchestra-gn3.4-17.12/web-ui/src/main/resources/catalog/components/filestore/FileStoreDirective.js#L52

Will have to do some testing to see if changing it to 'private' makes sane defaults again, or if more things have to be tweaked.

**Comment by landryb** [comment]
landryb/geonetwork@7acb3338 fixes the default upload mode, needs testing now.

**Comment by landryb** [comment]
Hmm, seems this is not enough as attaching a new file calls `POST /geonetwork/srv/api/0.1/records/b86ef124-6a85-4d7f-b71f-cd231557bf71/attachments?visibility=public` and the attachment is public. Dammit.

**Comment by landryb** [comment]
Ah no, it actualluy works/uploads the file as `private` by default once i've cleared the wro4j cache and fully reloaded the editor. Phew.

**Comment by fvanderbiest** [comment]
Closing, as I think we've come up to a conclusion here. Please reopen if required.

**Comment by landryb** [comment]
Ideally georchestra/geonetwork#82 should be merged, but yeah this particular issue can be closed.
