### ISSUE TITLE
No branch for geonetwork 3.8.2

### ISSUE THREAD

**Issue by pmauduit** [georchestra/geonetwork_minimal_datadir#5]
There are no branch in this repository for the version 3.8.2.

I am wondering though if this is necessary, as it will be bootstraped by what is bundled in the webapp anyway.

If this is not necessary anymore, we might want to fix the official setup doc around here:
https://github.com/georchestra/georchestra/blob/master/docs/setup/tomcat.md#geonetwork-30x-georchestra-1512-and-above

**Comment by landryb** [comment]
https://github.com/georchestra/geonetwork_minimal_datadir/commit/6a476468634e553ea2b88b23c7dd6f38d4114831 ?

**Comment by pmauduit** [comment]
In the newer versions of GN, there is now a tool to download the inspire thesauri automatically anyway

**Comment by fvanderbiest** [comment]
I think we need to create the branch anyway, at least for newcomers.
Can you take care of it ? Thanks

**Comment by fvanderbiest** [comment]
We'll have to change https://github.com/georchestra/ansible/blob/b61afdb60f4cb11914e260ca3b13472eeebcc822/playbooks/georchestra.yml#L77 at the same time

**Comment by fvanderbiest** [comment]
We have https://github.com/georchestra/geonetwork_minimal_datadir/tree/gn3.8.3
Should it be renamed @pmauduit ?

**Comment by pmauduit** [comment]
> Should it be renamed @pmauduit ?

I have no idea where this branch come from, last time I worked on a GN update in georchestra, it was for the v3.8.2

**Comment by pmauduit** [comment]
so yes, once the other issues have been fixed, I'd be in favor of renaming 3.8.3 in 3.8.2.

**Comment by pmauduit** [comment]
I created a branch 3.8.2 (which is actually a 3.8.3 with the schema_plugins subdirectory emptied).
