### ISSUE TITLE
XSD Validation error(s)

### ISSUE THREAD

**Issue by jusabatier** [georchestra/geonetwork_minimal_datadir#7]
When starting a GN with 3.8.3 branch, I get an error with XSD validation : 

```
Failed whilst validating schema-ident file /opt/gn_datadir/config/schema_plugins/iso19139/schema-ident.xml. Exception message if any is XSD Validation error(s):
<xsderrors>

  <error>

    <typeOfError>ERROR</typeOfError>

    <errorNumber>1</errorNumber>

    <message>cvc-complex-type.2.4.a: Invalid content was found starting with element 'title'. One of '{"http://geonetwork-opensource.org/schemas/schema-ident":appMinorVersionSupported}' is expected. (Element: title with parent element: schema)</message>

    <xpath>title[1]</xpath>

  </error>

</xsderrors>
```

**Comment by jusabatier** [comment]
Same problem for 'dublin-core', 'iso19110' and 'csw-record' schemas.

**Comment by pmauduit** [comment]
The schema should be provided by the Geonetwork webapp, not here.

In docker setups, we are pointing the schema_dir to the exploded webapp: 
https://github.com/georchestra/datadir/blob/docker-master/geonetwork/geonetwork.properties#L10

I think we should harmonize the behaviour across setups (ansible), and remove the schemas from this repository.

**Comment by landryb** [comment]
well originally i think the schemas were looked up in the datadir to allow user to customize them, i know at some point i had some fixes in it...

**Comment by landryb** [comment]
to fix the actual issue as discussed on irc, backport the XML bits from geonetwork/core-geonetwork@ac4c27d26d4a289728fd8a13480480657a402bc3 ?

**Comment by fvanderbiest** [comment]
> I think we should harmonize the behaviour across setups (ansible), and remove the schemas from this repository.

Standard geOrchestra datadir:
* master (not docker) has `geonetwork.schema.dir=${geonetwork.config.dir}/schema_plugins/` see https://github.com/georchestra/datadir/blob/4330e6ea2c63e2026fab4f65c082831108074c5b/geonetwork/geonetwork.properties#L10
*  docker-master has `geonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/` see https://github.com/georchestra/datadir/blob/a795bacecd9b6785832c0b3326a5d0b42a9491ae/geonetwork/geonetwork.properties#L10

What would you propose for master ? path is not predictable...
